export const authCopy = {
  signIn: {
    eyebrow: "Sign in",
    title: "Access Metis",
    intro: "Use Google, GitHub, a magic link, or your email and password",
    submitLabel: "Continue",
    alternateLabel: "Create account",
    alternateHref: "/sign-up",
    footerPrompt: "Need an account?",
  },
  signUp: {
    eyebrow: "Create account",
    title: "Start with Metis",
    intro: "Create access with Google, GitHub, a magic link, or email and password",
    submitLabel: "Create account",
    alternateLabel: "Sign in",
    alternateHref: "/sign-in",
    footerPrompt: "Already have access?",
  },
  shared: {
    brandLabel: "Metis Web",
    signInTab: "Sign in",
    signUpTab: "Sign up",
    providerLabel: "Continue with",
    googleLabel: "Google",
    githubLabel: "GitHub",
    magicLinkLabel: "Send magic link",
    magicLinkSuccess: "Magic link sent. Check your inbox and continue from the email.",
    emailDividerLabel: "or use email",
    emailLabel: "Work email",
    emailPlaceholder: "you@company.com",
    passwordLabel: "Password",
    passwordPlaceholder: "Enter your password",
    createPasswordPlaceholder: "Create a password",
    forgotPasswordLabel: "Forgot password?",
    verificationMessage: "Check your inbox and confirm your email before signing in.",
    backToSite: "Back to the site",
    missingCredentialsMessage: "Email and password are both required.",
    missingEmailMessage: "Enter your email first so we know where to send the message.",
    passwordMismatchMessage: "Passwords need to match before you can continue.",
    providerLaunchError: "The provider sign-in could not start.",
    magicLinkError: "The magic link could not be sent.",
    createAccountError: "We could not create that account.",
    signInError: "That email and password combination did not work.",
    resetRequestError: "We could not send a recovery email right now.",
    resetRequestSuccess: "Recovery email sent. Check your inbox for the reset link.",
    resetPasswordError: "We could not update your password right now.",
    resetPasswordSuccess: "Password updated. You can sign in now.",
    resetPasswordExpired: "That reset link is expired or incomplete.",
  },
  verify: {
    eyebrow: "Verify email",
    title: "Check your inbox",
    intro: "Open the email from Metis and use the secure link to finish access.",
    body: "Once verification is complete you can return to sign in and move into onboarding.",
    emailLabel: (email: string) => `Verification sent to ${email}`,
    primaryLabel: "Back to sign in",
    secondaryLabel: "Create another account",
  },
  forgotPassword: {
    eyebrow: "Recovery",
    title: "Reset your password",
    intro: "Enter your email and we will send a recovery link.",
    submitLabel: "Send recovery email",
    successTitle: "Check your inbox",
    successBody: (email: string) => `We sent a recovery link to ${email}. Open it on this device to choose a new password.`,
    backLabel: "Back to sign in",
  },
  resetPassword: {
    eyebrow: "New password",
    title: "Choose a new password",
    intro: "Enter your new password to finish recovery.",
    submitLabel: "Update password",
    passwordConfirmLabel: "Confirm password",
    passwordConfirmPlaceholder: "Confirm your password",
    invalidTitle: "Recovery link needed",
    invalidBody: "Use a fresh recovery email so Metis can confirm it is really you.",
    successTitle: "Password updated",
    successBody: "You can sign in now and move straight back into Metis.",
    successLabel: "Go to sign in",
  },
  loggedIn: {
    eyebrow: "Setup",
    title: "What should Metis focus on first",
    readyForYou: "Pick the answers that fit. You can choose more than one in each group.",
    readyForEmail: (email: string) => `Signed in as ${email}`,
    panelBody: "This first pass stays short. It helps shape what Metis should prioritize next for you.",
    signOutLabel: "Sign out",
    finishLabel: "Finish setup",
    skipLabel: "Skip for now",
    completionEyebrow: "Saved",
    completionTitle: "Your setup is captured",
    completionBody: "You are in. More features are coming soon, and this first setup pass is now recorded.",
    questions: [
      {
        id: "role",
        title: "Who are you setting Metis up for",
        helper: "Choose every role that fits",
        options: ["Founder", "Engineer", "Product", "Design", "Growth", "Ops"],
      },
      {
        id: "goals",
        title: "What should Metis help with first",
        helper: "Choose more than one if needed",
        options: ["Cost visibility", "AI spend", "Fix priority", "Team reporting", "Site audits", "Release checks"],
      },
      {
        id: "stack",
        title: "What shows up most in your stack",
        helper: "Pick the tools or surfaces you expect Metis to touch first",
        options: ["Next.js", "React", "Vercel", "OpenAI", "Cloudflare", "Third party scripts"],
      },
    ],
  },
} as const;
