export const authCopy = {
  signIn: {
    eyebrow: "Access",
    title: "Sign in to Metis",
    intro: "Choose a provider, use a magic link, or sign in with email and password",
    submitLabel: "Sign in",
    alternateLabel: "Create an account",
    alternateHref: "/sign-up",
    panelTitle: "Get back into the product",
    panelBody: "Use the fastest path into Metis and move straight from access into setup",
    steps: ["Choose", "Verify", "Start"],
    highlights: [
      "Use Google or GitHub if you want the quickest path",
      "Use a magic link if you do not want to enter a password",
      "Land inside the guided onboarding flow as soon as access is valid",
    ],
  },
  signUp: {
    eyebrow: "Start",
    title: "Create your Metis access",
    intro: "Start with Google, GitHub, magic link, or create access with email and password",
    submitLabel: "Create account",
    alternateLabel: "Already have access",
    alternateHref: "/sign-in",
    panelTitle: "Move from sign up into setup",
    panelBody: "Create access now and continue directly into the onboarding questions that shape the next product pass",
    steps: ["Create", "Confirm", "Answer"],
    highlights: [
      "Choose the provider flow that feels easiest",
      "Use magic link when you want less friction",
      "Keep the first protected experience short and useful",
    ],
  },
  shared: {
    brandLabel: "Metis Web",
    stageLabel: "Access flow",
    switcherLabel: "Mode",
    signInTab: "Sign in",
    signUpTab: "Sign up",
    providerLabel: "Continue with a provider",
    googleLabel: "Continue with Google",
    githubLabel: "Continue with GitHub",
    magicLinkLabel: "Email me a magic link",
    magicLinkSuccess: "Magic link sent. Check your inbox and continue from the email",
    emailDividerLabel: "or use email and password",
    emailLabel: "Email",
    emailPlaceholder: "you@company.com",
    passwordLabel: "Password",
    passwordPlaceholder: "Enter a strong password",
    accessCardTitle: "Access first",
    accessCardBody: "Choose the path that gets you into Metis with the least friction",
    setupCardTitle: "Setup next",
    setupCardBody: "Answer a few questions so the first protected experience feels shaped around your needs",
    trustCardTitle: "Keep it clear",
    trustCardBody: "No hidden provider jumps, no confusing detours, and no fake completion state before onboarding starts",
    verificationMessage: "Check your inbox and confirm your email before signing in",
    backToSite: "Back to the site",
    missingCredentialsMessage: "Email and password are both required",
    missingEmailMessage: "Enter your email first so we know where to send the magic link",
    providerLaunchError: "The provider login could not start",
    magicLinkError: "The magic link could not be sent",
    createAccountError: "We could not create that account",
    signInError: "That email and password combination did not work",
  },
  loggedIn: {
    eyebrow: "Onboarding",
    title: "Tell Metis what matters first",
    readyForYou: "Answer a few quick questions and shape the first protected experience",
    readyForEmail: (email: string) => `Signed in as ${email}`,
    panelTitle: "White multi answer panel",
    panelBody: "Choose more than one answer when it helps. This step is here to guide the next product pass, not slow you down",
    signOutLabel: "Sign out",
    finishLabel: "Finish setup",
    skipLabel: "Skip for now",
    completionEyebrow: "Saved",
    completionTitle: "Your setup is captured",
    completionBody: "You can move on now and come back later when deeper onboarding persistence is wired",
    summaryTitle: "Protected access is working",
    summaryItems: [
      { title: "Session active", body: "Supabase has completed the auth handoff and the protected page is reachable" },
      { title: "Backend ready", body: "FastAPI is prepared to validate authenticated access for the next product routes" },
      { title: "Next surface", body: "Saved scans, richer reports, and team facing flows can now layer on top" },
    ],
    questions: [
      {
        id: "role",
        title: "Who are you setting Metis up for",
        helper: "Choose every role that fits",
        options: ["Founder", "Engineer", "Product", "Design", "Growth", "Ops"],
      },
      {
        id: "goals",
        title: "What should Metis help with first",
        helper: "Choose more than one if needed",
        options: ["Cost visibility", "AI spend", "Fix priority", "Team reporting", "Site audits", "Release checks"],
      },
      {
        id: "stack",
        title: "What shows up most in your stack",
        helper: "Pick the tools or surfaces you expect Metis to touch first",
        options: ["Next.js", "React", "Vercel", "OpenAI", "Cloudflare", "Third party scripts"],
      },
    ],
  },
} as const;
