export const authCopy = {
  signIn: {
    eyebrow: "Sign in",
    title: "Welcome back",
    intro: "Choose Google, GitHub, a magic link, or email and password to get back into Metis.",
    submitLabel: "Continue",
    alternateLabel: "Create account",
    alternateHref: "/sign-up",
    footerPrompt: "Need an account?",
  },
  signUp: {
    eyebrow: "Create account",
    title: "Start with Metis",
    intro: "Create your free account on the website, accept the legal terms here, and move straight into your first guided setup.",
    submitLabel: "Create account",
    alternateLabel: "Sign in",
    alternateHref: "/sign-in",
    footerPrompt: "Already have access?",
  },
  shared: {
    brandLabel: "Metis Web",
    stageTitle: "A quiet layer for frontend cost risk",
    stageBody:
      "Metis keeps the auth surface compact, secure, and focused so the product can move you quickly from access into signal.",
    signInTab: "Sign in",
    signUpTab: "Sign up",
    providerLabel: "Continue with",
    googleLabel: "Google",
    githubLabel: "GitHub",
    magicLinkLabel: "Send magic link",
    magicLinkSuccess: "Magic link sent. Check your inbox and continue from the email.",
    emailDividerLabel: "or use email",
    emailLabel: "Work email",
    emailPlaceholder: "you@company.com",
    passwordLabel: "Password",
    passwordPlaceholder: "Enter your password",
    createPasswordPlaceholder: "Create a password",
    forgotPasswordLabel: "Forgot password?",
    verificationMessage: "Check your inbox and confirm your email before signing in.",
    backToSite: "Back to the site",
    missingCredentialsMessage: "Email and password are both required.",
    missingEmailMessage: "Enter your email first so we know where to send the message.",
    passwordMismatchMessage: "Passwords need to match before you can continue.",
    providerLaunchError: "The provider sign-in could not start.",
    magicLinkError: "The magic link could not be sent.",
    createAccountError: "We could not create that account.",
    signInError: "That email and password combination did not work.",
    resetRequestError: "We could not send a recovery email right now.",
    resetRequestSuccess: "Recovery email sent. Check your inbox for the reset link.",
    resetPasswordError: "We could not update your password right now.",
    resetPasswordSuccess: "Password updated. You can sign in now.",
    resetPasswordExpired: "That reset link is expired or incomplete.",
    legalBlurb: "Protected access for metis.zward.studio",
    legalAcceptanceLabel: "I agree to the Terms of Use and Privacy Policy.",
    legalAcceptanceError: "You need to accept the Terms of Use and Privacy Policy before creating an account.",
    temporaryAccessLabel: "Local testing only",
    temporaryAccessBody: "Google is temporarily bypassed in local development so onboarding and account flows can be reviewed quickly.",
    temporaryAccessAction: "Use temporary Google test account",
    temporaryAccessError: "The temporary test account could not be started.",
  },
  verify: {
    eyebrow: "Verify email",
    title: "Check your inbox",
    intro: "Open the email from Metis and use the secure link to finish access.",
    body: "Once verification is complete you can return to sign in and move into onboarding without extra setup.",
    emailLabel: (email: string) => `Verification sent to ${email}`,
    primaryLabel: "Back to sign in",
    secondaryLabel: "Create another account",
  },
  forgotPassword: {
    eyebrow: "Recovery",
    title: "Reset your password",
    intro: "Enter your email and we will send a recovery link.",
    submitLabel: "Send recovery email",
    successTitle: "Check your inbox",
    successBody: (email: string) => `We sent a recovery link to ${email}. Open it on this device to choose a new password.`,
    backLabel: "Back to sign in",
  },
  resetPassword: {
    eyebrow: "New password",
    title: "Choose a new password",
    intro: "Enter your new password to finish recovery.",
    submitLabel: "Update password",
    passwordConfirmLabel: "Confirm password",
    passwordConfirmPlaceholder: "Confirm your password",
    invalidTitle: "Recovery link needed",
    invalidBody: "Use a fresh recovery email so Metis can confirm it is really you.",
    successTitle: "Password updated",
    successBody: "You can sign in now and move straight back into Metis.",
    successLabel: "Go to sign in",
  },
  loggedIn: {
    eyebrow: "Setup",
    title: "Tell Metis what matters first",
    readyForYou: "Answer three quick questions so Metis can shape the first pass around your product.",
    readyForEmail: (email: string) => `Signed in as ${email}`,
    panelBody: "This stays short and points your first dashboard toward the signals you care about most.",
    finishLabel: "Finish setup",
    skipLabel: "Skip for now",
    completionEyebrow: "Saved",
    completionTitle: "Your setup is captured",
    completionBody: "You are in. The first setup answers are saved and your account areas are ready to review next.",
    temporaryAccountLabel: "Temporary test account",
    temporaryAccountBody: "This local-only session is for reviewing onboarding and account flows. Remove it before shipping.",
    questions: [
      {
        id: "type",
        title: "What are you building?",
        helper: "We'll personalise your first scan for your project type.",
        options: ["SaaS app", "E-commerce", "Internal tool", "Something else"],
      },
      {
        id: "team",
        title: "How big is your team?",
        helper: "Helps us tune how we present team-level insights.",
        options: ["Just me", "2 – 5", "6 – 20", "20+"],
      },
      {
        id: "concern",
        title: "What worries you most?",
        helper: "We'll surface those insights first on your dashboard.",
        options: ["API costs", "Performance", "AI spend", "All of it"],
      },
    ],
  },
  account: {
    eyebrow: "Account",
    title: "Manage your Metis account",
    subtitle: "Profile, access method, plan status, and secure entry points live here.",
    accountSectionTitle: "Account",
    accountSectionBody: "Identity basics, verification state, and a quick snapshot of what is ready.",
    verifiedLabel: "Verified",
    unverifiedLabel: "Verification pending",
    providerLabel: "Sign-in method",
    providerBody: "This account currently signs in through the method shown below.",
    pricingSectionTitle: "Plan & Pricing",
    pricingSectionBody: "Start free and keep pricing visible as Metis expands into Plus Beta and deeper dashboard access.",
    planLabel: "Current plan",
    planValue: "Metis Free",
    planBody: "Start free and enroll into Plus Beta when deeper dashboard access opens up.",
    securityTitle: "Security",
    securityBody: "Review your secure access settings and future two-factor options.",
    securityCta: "Open security settings",
    settingsSectionTitle: "Metis settings",
    settingsSectionBody: "The browser extension remains the place for lightweight controls and in-product settings.",
    appSettingsTitle: "App settings",
    appSettingsBody: "Extension settings will connect here once the browser entry point is wired.",
    appSettingsLinkLabel: "Extension settings link",
    appSettingsLinkState: "Inactive for now",
    signOutLabel: "Sign out",
    temporaryAccountLabel: "Temporary local account",
    temporaryAccountBody: "This session exists only for local auth review and does not grant backend API access.",
  },
  dashboard: {
    brandLabel: "Metis Dash",
    moreSectionsLabel: "More sections coming soon",
    betaBadge: "Plus Beta",
    sectionOrder: [
      { id: "account", label: "Account", subtitle: "Identity, verification, and connected access" },
      { id: "api", label: "API Beta", subtitle: "Staged API access, beta keys, and rollout status" },
      { id: "security", label: "Security", subtitle: "Sign-in method, 2FA preview, and staged account protection" },
      { id: "pricing", label: "Plan & Pricing", subtitle: "Free access and Plus Beta enrollment" },
      { id: "settings", label: "Settings", subtitle: "Extension settings entry point and in-product controls" },
    ],
    account: {
      title: "Account overview",
      body: "Keep identity basics, verification status, and connected access in one place.",
      profileStatusLabel: "Account status",
      freePlanLabel: "Free plan",
      plusBetaLabel: "Plus Beta",
      activeState: "Active",
      connectedAccountsTitle: "Connected access",
      connectedLabel: "Connected",
      availableLabel: "Available",
      primaryLabel: "Primary",
      usageTitle: "Scan usage",
      usageSummary: "139 of 50 scans",
      usageDetail: "Current account activity over the last 7 days",
      usageDelta: "+18% vs last week",
    },
    apiBeta: {
      title: "API Beta",
      body: "Preview the staged API surface for CI checks, deploy hooks, and automated scans without overstating what is live.",
      accessTitle: "Beta access status",
      pendingLabel: "Pending unlock",
      enabledLabel: "Enabled for Plus Beta",
      accessBody: "API Beta is staged while endpoints, rate limits, and docs are hardened for launch.",
      keyTitle: "Beta key preview",
      keyBody: "Keys stay masked until API Beta is enabled for this account.",
      keyPlaceholder: "beta_key_••••••••••••••••••",
      docsTitle: "Docs and endpoints",
      docsBody: "Read-only docs, rollout notes, and typed endpoint examples will ship during the beta period.",
      primaryCta: "Join Plus Beta",
      secondaryCta: "Docs coming soon",
      securityNote: "Never paste beta keys into client-side code. Keep all tokens server-side.",
    },
    security: {
      title: "Security posture",
      body: "Keep the current sign-in method visible, preview two-factor, and stage deeper controls honestly.",
      scoreTitle: "Good security posture",
      scoreBody: "Email verification, provider auth, and recovery flows are active. Two-factor is next.",
      providerTitle: "Sign-in method",
      providerBody: "This account currently signs in through the method shown below.",
      twoFactorTitle: "Two-factor authentication",
      twoFactorStatus: "Preview available",
      twoFactorBody: "The setup flow is designed and ready to review, but activation still depends on backend rollout.",
      twoFactorCta: "Open security preview",
      activeSessionsTitle: "Active sessions",
      auditLogTitle: "Audit log",
      comingSoonLabel: "Coming soon",
      comingSoonBody: "These controls stay visible so the dashboard is honest about what is next without pretending the backend is already live.",
    },
    pricing: {
      title: "Plan & Pricing",
      body: "Start free, then enroll into Plus Beta when you need deeper dashboard and API access.",
      monthlyLabel: "Monthly",
      annualLabel: "Annual",
      annualSavingsLabel: "2 months free",
      plans: [
        {
          id: "free",
          name: "Free",
          price: "$0",
          period: "forever",
          desc: "For individuals exploring Metis.",
          cta: "Current plan",
          current: true,
          highlight: false,
          features: ["50 page scans / month", "3 tracked sites", "Core issue detection", "7-day history"],
          missing: ["API Beta", "Plus Beta insights", "Priority support"],
        },
        {
          id: "plus_beta",
          name: "Plus Beta",
          price: "$12",
          period: "/ month",
          desc: "For early members who want API Beta, deeper signals, and staged premium access.",
          cta: "Enroll in Plus Beta",
          current: false,
          highlight: true,
          features: [
            "Unlimited scans",
            "20 tracked sites",
            "AI scoring + fix suggestions",
            "90-day history",
            "API Beta access",
            "Priority support",
          ],
          missing: [],
        },
      ],
      faq: [
        { q: "Can I switch plans later?", a: "Yes. Free remains available, and Plus Beta can be enabled or removed during the staged rollout." },
        { q: "What does Plus Beta unlock?", a: "It stages deeper dashboard access, API Beta, and premium rollout features as they harden." },
        { q: "Is there a Team plan?", a: "Not in this phase. The dashboard is focused on Free and Plus Beta only." },
      ],
    },
    settings: {
      title: "Settings",
      body: "Keep extension settings as the single settings entry point for now.",
      appSettingsTitle: "App settings",
      appSettingsBody: "This opens the extension settings entry point once the browser hook is wired.",
      appSettingsState: "Extension route only",
    },
    temporaryAccountBody: "Temporary local account. This dashboard is for review only and does not grant backend API access.",
    unverifiedBody: "Email verification is still pending. This preview stays visible, but the full production auth path requires a confirmed address.",
  },
  security: {
    eyebrow: "Security",
    title: "Protect your Metis access",
    subtitle: "Set up two-factor authentication, review your current sign-in method, and keep the account boundary explicit.",
    currentProtectionTitle: "Available now",
    currentProtectionItems: [
      "Supabase session handling",
      "Email verification checks",
      "Provider-based sign-in with Google and GitHub",
      "Password recovery with callback validation",
    ],
    currentProtectionBody: "These protections are active now and cover the current access flow.",
    nextProtectionTitle: "Coming next",
    nextProtectionItems: [
      "Recovery codes",
      "Trusted device review",
      "Session management for teams",
    ],
    nextProtectionBody: "These surfaces are designed now, but they still require backend activation before they become live controls.",
    previewTitle: "Two-factor authentication",
    previewBody: "Temporary accounts can still review the 2FA layout here, but real accounts now use the live authenticator-app flow below.",
    previewLocked: "Preview only",
    setupBadge: "Start setup",
    enabledBadge: "Enabled",
    setupBody: "Use an authenticator app like 1Password, Authy, or Google Authenticator to add a second sign-in step.",
    previewOnlyBody: "Two-factor stays in preview for temporary local accounts. Use a real account to enroll a TOTP factor and verify a live six-digit code.",
    startTitle: "Authenticator app",
    startBody: "Begin setup to generate a QR code and secret for your authenticator app. Once verified, the current session is promoted to aal2.",
    startCta: "Start 2FA setup",
    manualKeyLabel: "Manual key",
    copyLabel: "Copy",
    copiedLabel: "Copied",
    verifyTitle: "Verify your code",
    verifyBody: "Scan the QR code or enter the manual key in your authenticator app, then enter the current six-digit code to finish setup.",
    codePlaceholder: "Enter 6-digit code",
    verifyCta: "Verify and enable",
    restartCta: "Restart setup",
    restartBody: "An earlier TOTP setup was started but not finished. Restart it to generate a fresh QR code and secret.",
    enabledTitle: "Authenticator active",
    enabledBody: (factorName: string) => `Two-factor is currently enabled for ${factorName}. The current session is already operating at the higher assurance level.`,
    enabledSummary: "Authenticator-based sign-in is live for this account. Keep your app and secret safe.",
    enabledPreviewMessage: "Use your authenticator app at your next sign-in to complete the second factor challenge.",
    reverifyCta: "Review 2FA details",
    disableCta: "Disable 2FA",
    loadError: "We could not load your current two-factor state right now.",
    enrollError: "We could not start two-factor setup right now.",
    enrollSuccess: "Authenticator setup started. Scan the QR code and verify the first code.",
    restartError: "We could not reset the unfinished setup. Try again.",
    invalidCode: "Enter the current 6-digit code from your authenticator app.",
    verifyError: "That verification code did not work. Try the latest code from your authenticator app.",
    verifySuccess: "Two-factor authentication is now enabled for this account.",
    disableError: "We could not disable two-factor authentication right now.",
    disableSuccess: "Two-factor authentication has been removed from this account.",
    loadingLabel: "Loading your current security state…",
    defaultFactorName: "Metis Authenticator",
    issuer: "Metis",
    assuranceTitle: "Authenticator assurance",
    currentLevelLabel: "Current level",
    nextLevelLabel: "Next level",
    assuranceBody: "AAL shows how strongly the current session is verified. aal2 means the session has passed both the first factor and a verified MFA factor.",
    twoFactorEnabledListItem: "Authenticator-based two-factor enabled",
    providerSectionTitle: "Current sign-in method",
    providerSectionBody: "Your current provider determines whether password changes happen here or with the provider you used to sign in.",
    sessionNote: "Protected routes stay private and are excluded from public indexing.",
    backLabel: "Back to account",
    temporaryAccountLabel: "Temporary security preview",
    temporaryAccountBody: "This local-only account can review the security UI, but it does not represent a real provider-backed session.",
  },
} as const;
